import { date as DateUtils } from 'quasar'

const format = (e: string) => {
	const split = e.split('-')
	const temp = { year: +split[0], month: +split[1], day: +split[2] }
	let date = DateUtils.buildDate(temp)
	return DateUtils.formatDate(date, 'DD MMM YY', {
		monthsShort: [
			'янв',
			'фев',
			'мар',
			'апр',
			'май',
			'июн',
			'июл',
			'авг',
			'сен',
			'окт',
			'ноя',
			'дек',
		],
	})
}

const tags = [
	{ id: 0, selected: false, label: 'one' },
	{ id: 1, selected: false, label: 'two' },
	{ id: 2, selected: false, label: 'three' },
	{ id: 3, selected: false, label: 'four' },
	{ id: 4, selected: false, label: 'five' },
	{ id: 5, selected: false, label: 'cix' },
]

const cols: Column[] = [
	{ id: 7, name: 'id', label: 'id', field: 'id', align: 'left', sortable: true },
	{ id: 3, name: 'name', label: 'Название', field: 'name', align: 'left', sortable: true },
	{ id: 1, name: 'client', label: 'Приложение', field: 'client', align: 'left', sortable: true },
	{ id: 2, name: 'field', label: 'Раздел', field: 'field', align: 'left', sortable: true },
	{ id: 0, name: 'date', label: 'Дата', field: 'date', align: 'right', sortable: true },
	{ id: 4, name: 'descr', label: 'Примеч.', field: 'descr', align: 'left', sortable: false },
	// { id: 5, name: 'actions', label: 'action', field: 'actions', align: 'right', sortable: false },
]

const rows = [
	{
		id: 0,
		name: 'Mercury UI',
		date: format('19-09-06'),
		client: 'web-client',
		field: 'концепт',
		descr: 'Mercury OS inspired. Недоделан.',
		url: 'https://amba-git-prior-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'mercury',
		expand: false,
	},
	{
		id: 1,
		name: 'Конструктор разметок (mercury)',
		date: format('19-08-02'),
		client: 'web-client',
		field: 'конструктор',
		descr: 'Mercury OS inspired. Недоделан.',
		url: 'https://mercury-phi.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'constructor-razmetok',
		expand: false,
	},
	{
		id: 2,
		name: 'PWA',
		date: format('19-07-12'),
		client: 'web-client',
		field: 'концепт',
		descr: 'Концепт веб-клиента',
		url: 'https://pwa-lemon.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'pwa',
		expand: false,
	},
	{
		id: 3,
		name: 'Конструктор согласований (старый)',
		date: format('18-02-22'),
		client: 'web-client',
		field: 'конструктор',
		descr: 'Делал давно совместно с дигдезом.',
		url: 'https://ks-beta.vercel.app/',
		tags: [],
		children: false,
		latest: false,
		pic: 'ks',
		expand: false,
	},
	{
		id: 4,
		name: 'Визуализация маршрута согласования',
		date: format('20-01-21'),
		client: 'web-client',
		field: 'ход согласования',
		descr: 'Показ различных веток в визе, в зависимости от исхода этапа',
		url: 'https://cycle-lilac.vercel.app/',
		tags: [],
		children: false,
		latest: false,
		pic: 'cycle',
		expand: false,
	},
	{
		id: 5,
		name: 'Визуализация маршрута согласования',
		date: format('20-11-17'),
		client: 'web-client',
		field: 'ход согласования',
		descr: 'Привязка к таймлайну',
		url: 'https://sogl.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'vis-timeline',
		expand: false,
	},
	{
		id: 6,
		name: 'Поведение кнопок',
		date: format('20-05-29'),
		client: 'web-client',
		field: 'все',
		descr: 'Поведение кнопок в разных ситуациях',
		url: 'https://trip-emptyfortress.vercel.app/#/btn',
		tags: [],
		children: false,
		latest: false,
		pic: 'buttons',
		expand: false,
	},
	{
		id: 7,
		name: 'Грид с липким заголовком',
		date: format('20-11-10'),
		client: 'web-client',
		field: 'грид',
		descr: 'залипание заголовка грида',
		url: 'https://trip-emptyfortress.vercel.app/#/sticky',
		tags: [],
		children: false,
		latest: false,
		pic: 'sticky',
		expand: false,
	},
	{
		id: 8,
		name: 'Новое УД (создание)',
		date: format('20-09-04'),
		client: 'web-client',
		field: 'УД',
		descr: 'Создание документа',
		url: 'https://trip-by4y2hici.vercel.app/#/create',
		tags: [],
		children: false,
		latest: false,
		pic: 'create',
		expand: false,
	},
	{
		id: 9,
		name: 'Новое УД (просмотр)',
		date: format('20-04-10'),
		client: 'web-client',
		field: 'УД',
		descr: 'Просмотр документа',
		url: 'https://trip-by4y2hici.vercel.app/#/delo',
		tags: [],
		children: false,
		latest: false,
		pic: 'prosmotr',
		expand: false,
	},
	{
		id: 10,
		name: 'Новое УД (переделки)',
		date: format('20-09-05'),
		client: 'web-client',
		field: 'УД',
		descr: 'Переделки после тестирования',
		url: 'https://trip-emptyfortress.vercel.app/#/delo',
		tags: [],
		children: false,
		latest: false,
		pic: 'peredelki',
		expand: false,
	},
	{
		id: 11,
		name: 'Веб-админка',
		date: format('20-10-07'),
		client: 'admin',
		field: 'все',
		descr: 'Упрощенный вариант админки',
		url: 'https://houston-omega.vercel.app/#/',
		tags: [],
		children: true,
		latest: false,
		pic: 'admin',
		expand: true,
		child: [
			{
				id: 11.1,
				name: 'Хьюстон',
				date: '20-08-11',
				descr: 'Первоначальный вариант админки',
				url: 'https://houston-nqzs9dnr0.vercel.app/#/',
			},
		],
	},
	{
		id: 12,
		name: 'Хьюстон',
		date: format('20-09-05'),
		client: 'admin',
		field: 'дашборд',
		descr: 'Первоначальный вариант админки',
		url: 'https://houston-nqzs9dnr0.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'houston',
		expand: false,
	},
	{
		id: 13,
		name: 'Персональный дашборд',
		date: format('20-12-10'),
		client: 'web-client',
		field: 'дашборд',
		descr: 'Персональный дашборд для СУЭК',
		url: 'https://personal-opal-psi.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'personal',
		expand: false,
	},
	{
		id: 14,
		name: 'Служебная записка ЛГНХ',
		date: format('20-11-26'),
		client: 'web-client',
		field: 'карточка',
		descr: 'Варианты разметок для вебинара по ЛГНХ',
		url: 'https://card-emptyfortress.vercel.app/#/doc1',
		tags: [],
		children: false,
		latest: false,
		pic: 'slujebka',
		expand: false,
	},
	{
		id: 15,
		name: 'Поиск в папке ЛГНХ',
		date: format('21-04-15'),
		client: 'web-client',
		field: 'карточка',
		descr: 'Результаты поиска в текущей папке ЛГНХ',
		url: 'https://elastic-git-lgnh-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'searchLgnh',
		expand: false,
	},
	{
		id: 16,
		name: 'Elastic',
		date: format('20-12-18'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Первая версия поиска, самая полная',
		url: 'https://elastic-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elastic',
		expand: false,
	},
	{
		id: 17,
		name: 'Elastic simple',
		date: format('21-03-21'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Упрощенная версия поиска',
		url: 'https://elastic-git-simple-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elasticsimple',
		expand: false,
	},
	{
		id: 18,
		name: 'Elastic middle',
		date: format('21-03-29'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Усредненная версия поиска',
		url: 'https://elastic-git-middle-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elasticmiddle',
		expand: false,
	},
	{
		id: 19,
		name: 'Elastic scroll',
		date: format('21-03-30'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Версия поиска со скроллами в агрегатах',
		url: 'https://elastic-git-middle1-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elasticscroll',
		expand: false,
	},
	{
		id: 20,
		name: 'Elastic tabs',
		date: format('21-04-14'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Поиск с табами в области агрегатов',
		url: 'https://elastic-git-tab-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elastictabs',
		expand: false,
	},
	{
		id: 21,
		name: 'Elastic light design',
		date: format('21-04-22'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Облегченный дизайн тулбара в результатах поиска',
		url: 'https://elastic-git-design-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elasticlight',
		expand: false,
	},
	{
		id: 22,
		name: 'Elastic group',
		date: format('21-05-07'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Группировка результатов поиска',
		url: 'https://elastic-git-group-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elasticgroup',
		expand: false,
	},
	{
		id: 23,
		name: 'Elastic lenta',
		date: format('21-07-27'),
		client: 'web-client',
		field: 'поиск',
		descr: 'Переключатель грид-лента в результатах поиска',
		url: 'https://elastic-gjuc2iike-emptyfortress.vercel.app/#/',
		tags: [],
		children: false,
		latest: false,
		pic: 'elasticlenta',
		expand: false,
	},
	{
		id: 24,
		name: 'Справочник сотрудников',
		date: format('21-02-21'),
		client: 'web-client',
		field: 'справочник',
		descr: 'Справочник сотрудников',
		url: 'https://elastic-git-catalog-emptyfortress.vercel.app/#/catalog',
		tags: [],
		children: false,
		latest: false,
		pic: 'usercatalog',
		expand: false,
	},
	{
		id: 25,
		name: 'Storybook',
		date: format('21-02-01'),
		client: 'web-client',
		field: 'storybook',
		descr: 'Попытка исользовать storybook для компонентов',
		url: 'https://storybook-inky.vercel.app/?path=/story/docsvision-kit--%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5',
		tags: [],
		children: false,
		latest: false,
		pic: 'storybook',
		expand: false,
	},
	{
		id: 26,
		name: 'Мобильный ВК',
		date: format('21-04-13'),
		client: 'web-client',
		field: 'storybook',
		descr: 'Интерфейс мобильного ВК. Недоделано.',
		url: 'https://io-six.vercel.app/home',
		tags: [],
		children: false,
		latest: false,
		pic: 'mobile',
		expand: false,
	},
	{
		id: 27,
		name: 'Таблица исполнения',
		date: format('21-04-20'),
		client: 'web-client',
		field: 'контрол',
		descr: 'Контрол таблицы исполнения',
		url: 'https://v3-git-table-emptyfortress.vercel.app/',
		tags: [],
		children: false,
		latest: false,
		pic: 'tablisp',
		expand: false,
	},
	{
		id: 28,
		name: 'Таблица исполнения lines',
		date: format('21-04-24'),
		client: 'web-client',
		field: 'контрол',
		descr: 'Контрол таблицы исполнения с вертикальными линиями в дереве',
		url: 'https://v3-git-lines-emptyfortress.vercel.app/',
		tags: [],
		children: false,
		latest: false,
		pic: 'tablisplines',
		expand: false,
	},
	{
		id: 29,
		name: 'Таблица исполнения склейка',
		date: format('21-04-26'),
		client: 'web-client',
		field: 'контрол',
		descr: 'Контрол таблицы исполнения с объединенными полями для экономии места',
		url: 'https://v3-git-glue-emptyfortress.vercel.app/',
		tags: [],
		children: false,
		latest: false,
		pic: 'tablispglue',
		expand: false,
	},
	{
		id: 30,
		name: 'Совместное редактирование документа',
		date: format('21-07-08'),
		client: 'web-client',
		field: 'карточка',
		descr: 'Редактирование документа в браузере и управление доступом',
		url: 'https://editor-git-add-emptyfortress.vercel.app/#/docs/1',
		tags: [],
		children: false,
		latest: false,
		pic: 'editdoc',
		expand: false,
	},
]

export { tags, cols, rows }
